<link href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet" />
<link rel="stylesheet" href="<?php echo $this->basePath()?>/libraries/adminlte/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
<!-- Ionicons -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
<!-- Theme style -->
<link rel="stylesheet" href="<?php echo $this->basePath()?>/libraries/adminlte/AdminLTE.min.css">
<!-- AdminLTE Skins. Choose a skin from the css/skins
   folder instead of downloading all of them to reduce the load. -->
<link rel="stylesheet" href="<?php echo $this->basePath()?>/libraries/adminlte/_all-skins.min.css">
<style>
	li .active {
		background: #e7e7e7;
	}
	.content{
		padding-bottom: 100px;
	}
	.glyphicon-refresh-animate {
		-animation: spin .7s infinite linear;
		-ms-animation: spin .7s infinite linear;
		-webkit-animation: spinw .7s infinite linear;
		-moz-animation: spinm .7s infinite linear;
	}

	@keyframes spin {
		from { transform: scale(1) rotate(0deg);}
		to { transform: scale(1) rotate(360deg);}
	}
	  
	@-webkit-keyframes spinw {
		from { -webkit-transform: rotate(0deg);}
		to { -webkit-transform: rotate(360deg);}
	}

	@-moz-keyframes spinm {
		from { -moz-transform: rotate(0deg);}
		to { -moz-transform: rotate(360deg);}
	}
	
	.well{
		background-color: #d9534f;
		border: 1px solid #d43f3a;
		color:white;
	}
	
	.container{
		width : 100%;
	}
	
	.treeview{
		padding : 0px 10px 0px 10px !important;
	}
	
	.sidebar-menu li > a:hover {
		//background-color:lightgray;
		color:black;
	}
</style>
<div class="row">
	<div class="col-md-12">
	  <div class="row well" style="margin-bottom:0px;padding:20px;border-radius: 5px 5px 0px 0px">
		<div class="col-md-12">
			<div class="col-md-8"><label style="font-weight: unset;font-size:12px"><b style="font-size:25px"> Atribut NCX</b> Latlong (Level Address SA)</label></div>
			<div class="col-md-4 pull-right" style="padding-top: 30px;color:white"><label class="pull-right"><!--Last Update : <?php echo date('Y-m-d H:i:s')?>--></label></div>
		</div>
	  </div>
	  <div class="row" style="background-color: whitesmoke;border: 1px solid #e3e3e3;min-height:450px;border-radius: 0px 0px 5px 5px;padding: 15px;">
			<div class="col-md-3">
				<aside class="main-sidebar" style="padding: 0px 15px 15px 15px; !important;min-width:315px;border-radius:5px">
			<!-- sidebar: style can be found in sidebar.less -->
				<section class="sidebar">
				  <!-- /.search form -->
				  <!-- sidebar menu: : style can be found in sidebar.less -->
				  <ul class="sidebar-menu" style="padding: 0px; border:solid 1px #d9534f;min-height:450px;background: white;">
					<li class="header" style="background-color:#d9534f;"><h3 style="padding-top : 0px;margin:0px;font-size:15px;"><b style="color:white">Hirarki Rekon</b></li>
					<?php
					$aa = explode('/',strtok($_SERVER["REQUEST_URI"],'?'));
					$link = str_replace('detail','',str_replace('-detail','',$aa[3]));
					foreach($this->menu_rekon as $row){
						$active = "";
						foreach($row['index'] as $temp){
							if($temp == $link){
								$active = "active";
							}
						}
					?>
						<li class="treeview <?php echo $active;?>">
						  <a href="#">
							<i class="fa <?php echo $row['ICON']; ?>"></i> <span><?php echo $row['NAME'];?></span>
							<span class="pull-right-container">
							  <i class="fa fa-angle-left pull-right"></i>
							</span>
						  </a>
						  <?php if(!empty($row['detail'])){?>
							  <ul class="treeview-menu">
								<?php foreach($row['detail'] as $val){?>
								<li style="white-space: normal;" <?php if($val['LINK'] == $link){echo $active = "class='active'";}?>>
								  <a <?php if($val['LINK'] == $link){echo $active = "class='active'";}?> href="<?php if($val['LINK'] != '#' && $val['LINK'] != ''){$this->basePath()?>/ncxtools/tools/<?php echo $val['LINK'];}else{echo "#";}?>"><i class="fa fa-circle-o"></i> <?php echo $val['NAME']?>
								  </a>
								</li>
								<?php }?>
							  </ul>
						  <?php }?>
						</li>
					<?php
					}
					?>
				  </ul>
				</section>
				<!-- /.sidebar -->
			  </aside>
			</div>
		  <div class="col-md-9" style="min-height:450px;margin: 0px;background: white;padding: 20px;border: 1px lightgray solid;border-radius: 5px;">
				<table class="table table-hover table-strips" id="example">
					<thead>
						<tr>
							<th>No</th>
							<th>Status</th>
							<th>Jumlah Data</th>
							<th>Persentase</th>
							<th>Action</th>
						</tr>
					</thead>
					<tbody id="body-content">
						<tr>
							<td>1</td>
							<td>All Data</td>
							<td id="all_tot"><span class="glyphicon glyphicon-refresh glyphicon-refresh-animate"></span> Loading . . .</td>
							<td id="all_per"><span class="glyphicon glyphicon-refresh glyphicon-refresh-animate"></span> Loading . . .</td>
							<td><a href="<?php echo $this->basePath()?>/ncxtools/tools/detail-billing?stat=all" target="blank" class="btn btn-danger"><i class="glyphicon glyphicon-search"></i> Detail</a></td>
						</tr>
						<tr>
							<td>2</td>
							<td>Valid</td>
							<td id="val_tot"><span class="glyphicon glyphicon-refresh glyphicon-refresh-animate"></span> Loading . . .</td>
							<td id="val_per"><span class="glyphicon glyphicon-refresh glyphicon-refresh-animate"></span> Loading . . .</td>
							<td><a href="<?php echo $this->basePath()?>/ncxtools/tools/detail-billing?stat=VALID" target="blank" class="btn btn-danger"><i class="glyphicon glyphicon-search"></i> Detail</a></td>
						</tr>
						<tr>
							<td>3</td>
							<td>Not Valid</td>
							<td id="not_tot"><span class="glyphicon glyphicon-refresh glyphicon-refresh-animate"></span> Loading . . .</td>
							<td id="not_per"><span class="glyphicon glyphicon-refresh glyphicon-refresh-animate"></span> Loading . . .</td>
							<td><a href="<?php echo $this->basePath()?>/ncxtools/tools/detail-billing?stat=NOT VALID" target="blank" class="btn btn-danger"><i class="glyphicon glyphicon-search"></i> Detail</a></td>
						</tr>
					</tbody>
				</table>
		  </div>
		  <div class="col-md-12" style="padding:15px 0px 0px 30px">
			  <div id="kirim_toggle" style="display:none" class="pull-right">
				<button id="send" class="btn btn-danger" type="button">Kirim</button>
				<a class="btn btn-warning pull-left" href="<?php echo $this->basePath()?>/ncxtools/tools/bulktermin">Batal</a>
			  </div>
		  </div>
	  </div>
	</div>
	</form>
	<div id="modal-success-save" class="modal fade" tabindex="-1" role="dialog">
	  <div class="modal-dialog" role="document">
		<div class="modal-content">
		  <div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			<h4 class="modal-title modal-success">Status Perubahan Data</h4>
		  </div>
		  <div class="modal-body">
			<div id="success-info"></div>
		  </div>
		  <div class="modal-footer">
			<button type="button" class="btn btn-default" data-dismiss="modal">Tutup</button>
		  </div>
		</div>
	  </div>
	</div>
</div>
<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script src="<?php echo $this->basePath()?>/libraries/adminlte/app.min.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="<?php echo $this->basePath()?>/libraries/adminlte/demo.js"></script>
<script>
	$.ajax({
			url:"<?php echo $this->basePath()?>/ncxtools/data/getTotalBilling",  
			type:"POST",
			data : "",
			success:function(datax){
				if(datax.code == 0){
					$.each(datax.data, function (i, item){
						document.getElementById('all_tot').innerHTML = item.TOTAL;
						document.getElementById('val_tot').innerHTML = item.VALID;
						document.getElementById('not_tot').innerHTML = item.NOT_VALID;
						
						document.getElementById('all_per').innerHTML = (item.TOTAL_PERCENT)+" %";
						document.getElementById('val_per').innerHTML = (item.VALID_PERCENT)+" %";
						document.getElementById('not_per').innerHTML = (item.NOT_VALID_PERCENT)+" %";
					});
					
					
				}
			},
			error: function (xhr, ajaxOptions, thrownError) {
				alert(xhr.status);
				alert(thrownError);
			  }
	   });
</script>