<link href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet" />
<style>
	.content{
		padding-bottom: 100px;
	}
	.glyphicon-refresh-animate {
		-animation: spin .7s infinite linear;
		-ms-animation: spin .7s infinite linear;
		-webkit-animation: spinw .7s infinite linear;
		-moz-animation: spinm .7s infinite linear;
	}

	@keyframes spin {
		from { transform: scale(1) rotate(0deg);}
		to { transform: scale(1) rotate(360deg);}
	}
	  
	@-webkit-keyframes spinw {
		from { -webkit-transform: rotate(0deg);}
		to { -webkit-transform: rotate(360deg);}
	}

	@-moz-keyframes spinm {
		from { -moz-transform: rotate(0deg);}
		to { -moz-transform: rotate(360deg);}
	}
	
	.well{
		background-color: #d9534f;
		border: 1px solid #d43f3a;
		color:white;
	}
</style>
<div class="row">
	
	<div class="col-md-12">
	  <div class="row well" style="margin-bottom:0px;padding:20px;border-radius: 5px 5px 0px 0px">
		<div class="col-md-12">
			<div class="col-md-8"><h3>Order Data NCX dan TIBS</h3></div>
			<div class="col-md-4 pull-right" style="padding-top: 30px;color:white"><label class="pull-right">Last Update : <?php echo date('Y-m-d H:i:s')?></label></div>
		</div>
	  </div>
	  <div class="row" style="background-color: whitesmoke;border: 1px solid #e3e3e3;min-height:450px;border-radius: 0px 0px 5px 5px;padding: 15px;">
		  <div class="col-md-12" style="min-height:350px;margin: 0px;background: white;padding: 20px;border: 1px lightgray solid;border-radius: 5px;">
				<table class="table table-hover table-strips" id="example">
					<thead>
						<tr>
							<th>No</th>
							<th>Status</th>
							<th>Jumlah Data</th>
							<th>Persentase</th>
							<th>Action</th>
						</tr>
					</thead>
					<tbody id="body-content">
						<tr>
							<td>1</td>
							<td>All Data</td>
							<td id="all_tot"><span class="glyphicon glyphicon-refresh glyphicon-refresh-animate"></span> Loading . . .</td>
							<td id="all_per"><span class="glyphicon glyphicon-refresh glyphicon-refresh-animate"></span> Loading . . .</td>
							<td><a href="<?php echo $this->basePath()?>/ncxtools/tools/detail-billing?stat=all" target="blank" class="btn btn-danger"><i class="glyphicon glyphicon-search"></i> Detail</a></td>
						</tr>
						<tr>
							<td>2</td>
							<td>Valid</td>
							<td id="val_tot"><span class="glyphicon glyphicon-refresh glyphicon-refresh-animate"></span> Loading . . .</td>
							<td id="val_per"><span class="glyphicon glyphicon-refresh glyphicon-refresh-animate"></span> Loading . . .</td>
							<td><a href="<?php echo $this->basePath()?>/ncxtools/tools/detail-billing?stat=VALID" target="blank" class="btn btn-danger"><i class="glyphicon glyphicon-search"></i> Detail</a></td>
						</tr>
						<tr>
							<td>3</td>
							<td>Not Valid</td>
							<td id="not_tot"><span class="glyphicon glyphicon-refresh glyphicon-refresh-animate"></span> Loading . . .</td>
							<td id="not_per"><span class="glyphicon glyphicon-refresh glyphicon-refresh-animate"></span> Loading . . .</td>
							<td><a href="<?php echo $this->basePath()?>/ncxtools/tools/detail-billing?stat=NOT VALID" target="blank" class="btn btn-danger"><i class="glyphicon glyphicon-search"></i> Detail</a></td>
						</tr>
					</tbody>
				</table>
		  </div>
		  <div class="col-md-12" style="padding:15px 0px 0px 30px">
			  <div id="kirim_toggle" style="display:none" class="pull-right">
				<button id="send" class="btn btn-danger" type="button">Kirim</button>
				<a class="btn btn-warning pull-left" href="<?php echo $this->basePath()?>/ncxtools/tools/bulktermin">Batal</a>
			  </div>
		  </div>
	  </div>
	</div>
	</form>
	<div id="modal-success-save" class="modal fade" tabindex="-1" role="dialog">
	  <div class="modal-dialog" role="document">
		<div class="modal-content">
		  <div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			<h4 class="modal-title modal-success">Status Perubahan Data</h4>
		  </div>
		  <div class="modal-body">
			<div id="success-info"></div>
		  </div>
		  <div class="modal-footer">
			<button type="button" class="btn btn-default" data-dismiss="modal">Tutup</button>
		  </div>
		</div>
	  </div>
	</div>
</div>
<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script>
	$.ajax({
			url:"<?php echo $this->basePath()?>/ncxtools/data/getTotalBilling",  
			type:"POST",
			data : "",
			success:function(datax){
				if(datax.code == 0){
					$.each(datax.data, function (i, item){
						document.getElementById('all_tot').innerHTML = item.TOTAL;
						document.getElementById('val_tot').innerHTML = item.VALID;
						document.getElementById('not_tot').innerHTML = item.NOT_VALID;
						
						document.getElementById('all_per').innerHTML = (item.TOTAL_PERCENT)+" %";
						document.getElementById('val_per').innerHTML = (item.VALID_PERCENT)+" %";
						document.getElementById('not_per').innerHTML = (item.NOT_VALID_PERCENT)+" %";
					});
					
					
				}
			},
			error: function (xhr, ajaxOptions, thrownError) {
				alert(xhr.status);
				alert(thrownError);
			  }
	   });
</script>