<link href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet" />
<div class="row">
	<div class="col-md-12">
	  <div class="row well">
		<div class="col-md-12">
			<h3>History</h3>
			<p>History perubahan detail</p>
		</div>
	  </div>
	  <div class="row">
		  <div class="col-md-12">
		  <div class="col-md-12">
				<table class="table table-hover table-strips" id="example">
					<thead>
						<tr>
							<th>Date</th>
							<th>Order Id</th>
							<th>CA</th>
							<th>BA</th>
							<th>SA</th>
							<th>User Action</th>
							<th>Old Value</th>
							<th>New Value</th>
							<th>Action</th>
						</tr>
					</thead>
					<tbody id="body-content">

					</tbody>
				</table>
		  </div>
	  </div>
	</div>
	<div class="col-md-12">
	  <div id="container"></div>
	</div>
	<div id="modal-success-save" class="modal fade" tabindex="-1" role="dialog">
	  <div class="modal-dialog" role="document">
		<div class="modal-content">
		  <div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			<h4 class="modal-title modal-success">Status Perubahan Data</h4>
		  </div>
		  <div class="modal-body">
			<div id="success-info"></div>
		  </div>
		  <div class="modal-footer">
			<button type="button" class="btn btn-default" data-dismiss="modal">Tutup</button>
		  </div>
		</div>
	  </div>
	</div>
</div>
<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script>
	$("#example").dataTable();
	 </script> 
</script>