<script src="<?php echo $this->basePath(); ?>/libraries/datatables/jquery.dataTables.min.js"></script>
<script src="<?php echo $this->basePath(); ?>/libraries/datatables/dataTables.bootstrap.min.js"></script>
<script src="<?php echo $this->basePath(); ?>/libraries/datatables/dataTables.responsive.js"></script>
<script src="<?php echo $this->basePath(); ?>/libraries/datatables/dataTables.buttons.min.js"></script>
<style>
	.content{
		padding-bottom: 100px;
	}
	.glyphicon-refresh-animate {
		-animation: spin .7s infinite linear;
		-ms-animation: spin .7s infinite linear;
		-webkit-animation: spinw .7s infinite linear;
		-moz-animation: spinm .7s infinite linear;
	}

	@keyframes spin {
		from { transform: scale(1) rotate(0deg);}
		to { transform: scale(1) rotate(360deg);}
	}
	  
	@-webkit-keyframes spinw {
		from { -webkit-transform: rotate(0deg);}
		to { -webkit-transform: rotate(360deg);}
	}

	@-moz-keyframes spinm {
		from { -moz-transform: rotate(0deg);}
		to { -moz-transform: rotate(360deg);}
	}
	
	.well{
		background-color: #d9534f;
		border: 1px solid #d43f3a;
		color:white;
	}
	
	.example2_processing{
		border-color:white !important;
	}
</style>
<div class="row">
	
	<div class="col-md-12">
	  <div class="row well" style="margin-bottom:0px;padding:20px;border-radius: 5px 5px 0px 0px">
		<div class="col-md-12">
			<div class="col-md-8"><h3>Rekon CABA NCX dan TIBS Detail</h3></div>
			<div class="col-md-4 pull-right" style="padding-top: 30px;color:white"><label class="pull-right">Last Update : <?php echo date('Y-m-d H:i:s')?></label></div>
		</div>
	  </div>
	  <div class="row" style="background-color: whitesmoke;border: 1px solid #e3e3e3;min-height:450px;border-radius: 0px 0px 5px 5px;padding: 15px;">
		  <div class="col-md-12" style="min-height:350px;margin: 0px;background: white;padding: 20px;border: 1px lightgray solid;border-radius: 5px;">
				<table class="table table-hover table-strips" id="example2" style="margin-bottom:0px !important">
					<thead>
						<tr>
							<th>No</th>
							<th>Ncx Last Update</th>
							<th>NCX CA</th>
							<th>NCX BA</th>
							<th>TIBS CA</th>
							<th>TIBS BA</th>
							<th>Status</th>
						</tr>
					</thead>
					<tbody id="body-content">

					</tbody>
				</table>
		  </div>
		  <div class="col-md-12" style="padding:15px 0px 0px 30px">
			  <div id="kirim_toggle" style="display:none" class="pull-right">
				<button id="send" class="btn btn-danger" type="button">Kirim</button>
				<a class="btn btn-warning pull-left" href="<?php echo $this->basePath()?>/ncxtools/tools/bulktermin">Batal</a>
			  </div>
		  </div>
	  </div>
	</div>
	</form>
	<div id="modal-success-save" class="modal fade" tabindex="-1" role="dialog">
	  <div class="modal-dialog" role="document">
		<div class="modal-content">
		  <div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			<h4 class="modal-title modal-success">Status Perubahan Data</h4>
		  </div>
		  <div class="modal-body">
			<div id="success-info"></div>
		  </div>
		  <div class="modal-footer">
			<button type="button" class="btn btn-default" data-dismiss="modal">Tutup</button>
		  </div>
		</div>
	  </div>
	</div>
</div>
<script>
	$('#example2').dataTable( {
		"serverSide": true,
		"processing": true,
        "language": {
            processing: '<span class="pull-center"><tr><td colspan="7" style="text-align : center;padding : 10px 0px;"><img src="<?php echo $this->basePath()?>/images/spinner.gif" width="20px" height="20px"> Loading . . .</td></tr></span> '},
		"ajax": {
			"url": "<?php echo $this->basePath(); ?>/ncxtools/data/getReconDetail",
			"type": 'POST',
			"data" : {
				STATUS : '<?php echo $_GET['stat']?>'
			},
		},
		"columns": [
			{ "data": "RNUM" },
			{ "data": "NCX_LAST_UPDATE" },
			{ "data": "NCX_CA" },
			{ "data": "NCX_BA" },
			{ "data": "TIBS_CA" },
			{ "data": "TIBS_BA" },
			{ "data": "STATUS" },
		],
	} );
</script>