<script>
	//$('body.vanilla').html("");
</script>
<?php
/* header("Content-type: application/octet-stream");
header("Content-Disposition: attachment; filename=detail_order_".date('d-m-Y').".xls");//ganti nama sesuai keperluan
header("Pragma: no-cache");
header("Expires: 0");
echo "<table>";
	echo "<tr>";
		echo "<th></th>";
		echo "<th></th>";
		echo "<th></th>";
		echo "<th></th>";
		echo "<th></th>";
	echo "</tr>";
echo "</table>"; */
?>
