<link href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet" />
<style>
	.content{
		padding-bottom: 100px;
	}
</style>
<div class="row">
	<div class="col-md-12">
	  <div class="row well" style="margin-bottom:0px;padding:20px;border-radius: 5px 5px 0px 0px">
		<div class="col-md-12">
			<h3>Job Post</h3>
			<p>update value action form</p>
		</div>
	  </div>
	  <div class="row" style="background-color: whitesmoke;border: 1px solid #e3e3e3;min-height:450px;border-radius: 0px 0px 5px 5px;padding-top: 30px;">
		  <div class="col-md-8">
			<div class="box-body">
				<div class="form-group row">
					<label class="col-sm-4">Customer Name</label>
					<div class="col-sm-8">
						<input type="text" class="form-control form-control-sm" value="" id="ca">
					</div>
				</div>
				<div class="form-group row">
					<label class="col-sm-4">Customer Address</label>
					<div class="col-sm-8">
						<input type="text" class="form-control form-control-sm" value="" id="ca">
					</div>
				</div>
				<div class="form-group row">
					<label class="col-sm-4">Order Id</label>
					<div class="col-sm-8">
						<input type="text" class="form-control form-control-sm" value="" id="ca">
					</div>
				</div>
				<div class="form-group row">
					<label class="col-sm-4">Account Id</label>
					<div class="col-sm-8">
						<input type="text" class="form-control form-control-sm" value="" id="ca">
					</div>
				</div>
				<div class="form-group row">
					<label class="col-sm-4">Customer Account</label>
					<div class="col-sm-8">
						<input type="text" class="form-control form-control-sm" value="" id="ca">
					</div>
				</div>
				<div class="form-group row">
					<label class="col-sm-4">Billing Account</label>
					<div class="col-sm-8">
						<input type="text" class="form-control form-control-sm" value="" id="ba">
					</div>
				</div>
				<div class="form-group row">
					<label class="col-sm-4">Service Account</label>
					<div class="col-sm-8">
						<input type="text" class="form-control form-control-sm" value="" id="sa">
					</div>
				</div>
				<div class="form-group row">
					<label class="col-sm-4">Order Fulfillment Status</label>
					<div class="col-sm-8">
						<input type="text" class="form-control form-control-sm" value="" id="sa">
					</div>
				</div>
				<div class="form-group row">
					<label class="col-sm-4">Change Reason</label>
					<div class="col-sm-8">
						<textarea class="form-control form-control-sm" value="" id="sa"></textarea>
					</div>
				</div>
				<div class="form-group row">
					<div class="col-sm-12">
						<button class="btn btn-danger pull-right" id="search">Save</button>
					</div>
				</div>
			</div>
		  </div>
		  <div class="col-md-2">
		  </div>
	  </div>
	</div>
	<div id="modal-success-save" class="modal fade" tabindex="-1" role="dialog">
	  <div class="modal-dialog" role="document">
		<div class="modal-content">
		  <div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			<h4 class="modal-title modal-success">Status Perubahan Data</h4>
		  </div>
		  <div class="modal-body">
			<div id="success-info"></div>
		  </div>
		  <div class="modal-footer">
			<button type="button" class="btn btn-default" data-dismiss="modal">Tutup</button>
		  </div>
		</div>
	  </div>
	</div>
</div>
<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script>
	$(document).ready(function(){  
		  $('#excel_file').change(function(){  
			   $('#export_excel').submit();  
		  });
	}); 
	
	$("#example").dataTable({
	});
	 </script> 
</script>