<link href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet" />
<style>
	.content{
		padding-bottom: 100px;
	}
</style>
<div class="row">
	<div class="col-md-12">
	  <h3>Dashboard</h3>
	  <div class="row well" style="margin-bottom:0px;padding:20px;border-radius: 5px 5px 0px 0px">
		<div class="col-md-12">
			<div class="form-group">
				<div class="col-md-2">
					<label>Upload File</label>
				</div>
				<div class="col-md-6">
					<form mehtod="post" id="export_excel">  
						<input type="file" value="" placeholder="Silahkan masukan keyword pencarian.." name="excel_file" id="excel_file" class="form-control">
					</form>
				</div>
			</div>
		</div>
	  </div>
	  <div class="row" style="background-color: whitesmoke;border: 1px solid #e3e3e3;min-height:450px;border-radius: 0px 0px 5px 5px;padding-top: 30px;">
		  <div class="col-md-12">
				<table class="table table-hover table-strips" id="example">
					<thead>
						<tr>
							<th>Tabel</th>
							<th>Action</th>
							<th>Value</th>
							<th>ID</th>
							<th>Date</th>
						</tr>
					</thead>
					<tbody id="body-content">

					</tbody>
				</table>
		  </div>
	  </div>
	</div>
	<div class="col-md-12">
	  <div id="container"></div>
	</div>
	<div id="modal-success-save" class="modal fade" tabindex="-1" role="dialog">
	  <div class="modal-dialog" role="document">
		<div class="modal-content">
		  <div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			<h4 class="modal-title modal-success">Status Perubahan Data</h4>
		  </div>
		  <div class="modal-body">
			<div id="success-info"></div>
		  </div>
		  <div class="modal-footer">
			<button type="button" class="btn btn-default" data-dismiss="modal">Tutup</button>
		  </div>
		</div>
	  </div>
	</div>
</div>
<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script>
	$(document).ready(function(){  
		  $('#excel_file').change(function(){  
			   $('#export_excel').submit();  
		  });  
		  $('#export_excel').on('submit', function(event){  
			   event.preventDefault();  
			   $.ajax({
					url:"<?php echo $this->basePath()?>/ncxtools/data/upload-excel",  
					method:"POST",  
					data:new FormData(this),  
					contentType:false,  
					processData:false,  
					success:function(data){
						$.each(data.data, function(i, item){
							$('#body-content').append('<tr>'+
								'<td>'+item.tabel+'</td>'+
								'<td>'+item.action+'</td>'+
								'<td>'+item.value+'</td>'+
								'<td>'+item.id+'</td>'+
								'<td>'+item.date+'</td>'+
							''); 
						});
						$("#example").dataTable();
					}  
			   });
		  });  
	});  
	 </script> 
</script>