<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="homeurl" content="<?php echo($this->home); ?>" />
    <title><?php echo($this->title . (empty($this->tagline) ? '' : ' - ' . $this->tagline)); ?></title>
    <?php if (isset($this->libraries)) $this->libraries->printHeader($this->basePath()); ?>
  </head>
  <body class="vanilla outside">
    <div class="content">
      <div class="container">
        <div class="row">
          <div class="col-lg-4 col-md-6 col-sm-8 col-xs-12 col-lg-offset-4 col-md-offset-3 col-sm-offset-2 col-xs-offset-0 login">
            <div class="panel panel-default shadow">
              <div class="panel-heading"><span class="glyphicon glyphicon-log-in"></span> <?php echo($this->title); ?></div>
              <div class="panel-body">
                <form id="naf-login" class="form-horizontal">
                  <div class="form-group">
                    <label for="naf-login-user" class="col-sm-3 control-label">User</label>
                    <div class="col-sm-9">
                      <input type="text" class="form-control" id="naf-login-user" placeholder="Your user id">
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="naf-login-pass" class="col-sm-3 control-label">Password</label>
                    <div class="col-sm-9">
                      <input type="password" class="form-control" id="naf-login-pass" placeholder="The password">
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="col-sm-offset-3 col-sm-9">
                      <button type="button" id="naf-login-do" class="btn btn-default">Sign in</button>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="footer shadow">
      <div class="container">
        <div class="copyright">
          Vanilla Theme - Powered by Neuron Application Framework &copy; 2018
        </div>
      </div>
    </div>
  </body>
  <?php if (isset($this->libraries)) $this->libraries->printFooter($this->basePath()); ?>
</html>