<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta http-equiv="x-ua-compatible" content="ie=edge">

        <title><?php echo($this->title . (empty($this->tagline) ? '' : ' - ' . $this->tagline)); ?></title>
		<?php if (isset($this->libraries)) $this->libraries->printHeader($this->basePath()); ?>

        <!-- Fonts and icons -->
        <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath(); ?>/libraries/dashboard/css/roboto-fontface.css" />
        <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath(); ?>/fonts/material-design-icons/material-icons.css" />
		<link id="favicon" rel="shortcut icon" href="<?php echo $this->basePath(); ?>/images/icon.png" type="image/png">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
        <!-- CSS -->
        <link href="<?php echo $this->basePath(); ?>/assets/css/bootstrap.min.css" rel="stylesheet" />
        <link href="<?php echo $this->basePath(); ?>/libraries/dashboard/css/material-kit.min.css" rel="stylesheet" />

        <!-- JQuery -->
        <script src="<?php echo $this->basePath(); ?>/libraries/jquery/js/jquery.min.js" type="text/javascript"></script>
		
		<style>
		.header-filter:after {
			background-color: rgba(0,0,0,.3) !important;
		}
		
		.others {color:black}
			.page-header:after {
				background-color: rgba(0,0,0,0) !important;
			}
		</style>
    </head>

    <body class="login-page">
      <nav class="navbar navbar-primary navbar-transparent navbar-absolute">
        <div class="container">
          <div class="navbar-header">
            <a class="navbar-brand" href="../presentation.html"><img class="img" src="<?php echo $this->basePath()?>/libraries/dashboard/logo-telkom-white.png"/ width="100px" height="70px"></a>
          </div>

          <div class="collpase navbar-collapse">
          </div>
        </div>
      </nav>
      <div class="page-header header-filter" style="background-image: url('<?php echo $this->basePath(); ?>/images/StockSnap_EAP0KLXBA8.jpg'); ">
        <div class="container">
          <div class="row">
			<div class="col-md-4 col-md-offset-8 col-sm-6 col-sm-offset-3">
				<div class="card card-signup">
					<form id="naf-login" class="form-horizontal" method="POST">
						<div class="header header-danger text-center">
							<img class="img" height="100px" src="<?php echo $this->basePath(); ?>/images/ncx-logo-white.png" style="height:80px;padding:0px 20px" />
						</div>
						<div class="card-content">

							<div class="input-group">
								<span class="input-group-addon">
									<i class="fa fa-user"></i>
								</span>
								<div class="form-group is-empty" style="padding:0px 12px 0px 12px"><input type="text" class="form-control" id="naf-login-user" placeholder="Your user id"><span class="material-input"></span></div>
							</div>

							<div class="input-group">
								<span class="input-group-addon">
									<i class="fa fa-lock"></i>
								</span>
								<div class="form-group is-empty" style="padding:0px 12px 0px 12px"><input type="password" class="form-control" id="naf-login-pass" placeholder="The password"><span class="material-input"></span></div>
							</div>
						</div>
						<div class="footer text-center">
							<?php
								echo "<b style='color:red'>".$this->info."</b>";
							?>
						</div>
						<div class="footer text-center">
							<button type="submit" id="naf-login-do" class="btn btn-danger">SUBMIT</button>
						</div>
					</form>
				</div>
			</div>
          </div>
        </div>
  </body>
  <?php if (isset($this->libraries)) $this->libraries->printFooter($this->basePath()); ?>
  <script>	
	$('#naf-login').submit(function(){
		var data = {
			code:$('#naf-login-user').val(),
			password:$('#naf-login-pass').val()
		}
		$.ajax({
			url:"<?php echo $this->basePath()?>/composite/user/authenticate",  
			type:"POST",  
			data : {code:0, data:JSON.stringify(data)},
			success:function(data){
				if(data.code == 0){
					location.reload(); 
				}else{
					alert(data.info);
				}
			}
		});
		return false;
	});
  </script>
</html>