<?php
return array(
    /* module route */
    'router' => array(
        'routes' => array(
            'home' => array(
                'type' => 'Zend\Mvc\Router\Http\Literal',
                'options' => array(
                    'route' => '/ncxtools',
                    'defaults' => array(
                        '__NAMESPACE__' => 'Neuron\Application\Ncxtools\Controller',
                        'controller' => 'Index',
                        'action' => 'ogpdashboard',
                    ),
                ),
                'may_terminate' => true,
                'child_routes' => array(
                    'default' => array(
                        'type' => 'Segment',
                        'options' => array(
                            'route' => '/[:controller[/:action]]',
                            'constraints' => array(
                                'controller' => '[a-zA-Z][a-zA-Z0-9_-]*',
                                'action' => '[a-zA-Z][a-zA-Z0-9_-]*',
                            ),
                            'defaults' => array(
                            ),
                        ),
                    ),
                ),
            ),
            'login' => array(
                'type' => 'Zend\Mvc\Router\Http\Literal',
                'options' => array(
                    'route' => '/login',
                    'defaults' => array(
                        '__NAMESPACE__' => 'Neuron\Application\Ncxtools\Controller',
                        'controller' => 'Index',
                        'action' => 'index',
                    ),
                ),
                'may_terminate' => true,
            ),
            'logout' => array(
                'type' => 'Zend\Mvc\Router\Http\Literal',
                'options' => array(
                    'route' => '/logout',
                    'defaults' => array(
                        '__NAMESPACE__' => 'Neuron\Application\Ncxtools\Controller',
                        'controller' => 'Index',
                        'action' => 'logout',
                    ),
                ),
                'may_terminate' => true,
            ),
			'Tools' => array(
                'type'    => 'Segment',
                'options' => array(
                    'route'    => '/ncxtools/tools[/:action][/:id_detail]',
					'constraints' => array(
                                'action' => '[a-zA-Z][a-zA-Z0-9_-]*',
                                'id_detail' => '[a-zA-Z0-9._-]*'
                            ),
                    'defaults' => array(
                        '__NAMESPACE__' => 'Neuron\Application\Ncxtools\Controller',
                        'controller' => 'Tools',
                        'action'     => 'index',
                    ),
                ),
            ),
        ),
    ),
    /* controller namespace mapping */
    'controllers' => array(
        'invokables' => array(
            'Neuron\Application\Ncxtools\Controller\Index' => 'Neuron\Application\Ncxtools\Controller\Index',
			'Neuron\Application\Ncxtools\Controller\Data' => 'Neuron\Application\Ncxtools\Controller\Data',
			'Neuron\Application\Ncxtools\Controller\Tools' => 'Neuron\Application\Ncxtools\Controller\Tools',
			'Neuron\Application\Ncxtools\Controller\Dashboard' => 'Neuron\Application\Ncxtools\Controller\Dashboard',
        ),
    ),
    /* view map */
    'view_manager' => array(
        'template_map' => array(
            'layout/inside' => __DIR__ . '/../layout/inside.phtml',
            'layout/outside' => __DIR__ . '/../layout/outside.phtml',
            'layout/layoutblank' => __DIR__ . '/../layout/layoutblank.phtml',
            'neuron/ncxtools/controller/index/index' => __DIR__ . '/../view/index/index.phtml',
            'neuron/ncxtools/controller/index/ogpdashboard' => __DIR__ . '/../view/tools/ogpdashboard.phtml',
            'neuron/ncxtools/controller/tools/search' => __DIR__ . '/../view/tools/search.phtml',
            'neuron/ncxtools/controller/tools/upload' => __DIR__ . '/../view/tools/upload.phtml',
            'neuron/ncxtools/controller/tools/form' => __DIR__ . '/../view/tools/form.phtml',
            'neuron/ncxtools/controller/tools/detail' => __DIR__ . '/../view/tools/detail.phtml',
            'neuron/ncxtools/controller/tools/create' => __DIR__ . '/../view/tools/create.phtml',
            'neuron/ncxtools/controller/tools/report' => __DIR__ . '/../view/tools/report.phtml',
            'neuron/ncxtools/controller/tools/dashboard' => __DIR__ . '/../view/tools/dashboard.phtml',
            'neuron/ncxtools/controller/tools/master' => __DIR__ . '/../view/tools/master.phtml',
            'neuron/ncxtools/controller/tools/termin' => __DIR__ . '/../view/tools/termin.phtml',
            'neuron/ncxtools/controller/tools/order' => __DIR__ . '/../view/tools/order.phtml',
            'neuron/ncxtools/controller/tools/updateca' => __DIR__ . '/../view/tools/updateca.phtml',
            'neuron/ncxtools/controller/tools/updateba' => __DIR__ . '/../view/tools/updateba.phtml',
            'neuron/ncxtools/controller/tools/updatesa' => __DIR__ . '/../view/tools/updatesa.phtml',
            'neuron/ncxtools/controller/tools/mergeca' => __DIR__ . '/../view/tools/mergeca.phtml',
            'neuron/ncxtools/controller/tools/mergeba' => __DIR__ . '/../view/tools/mergeba.phtml',
            'neuron/ncxtools/controller/tools/mergesa' => __DIR__ . '/../view/tools/mergesa.phtml',
            'neuron/ncxtools/controller/tools/ogpdashboard' => __DIR__ . '/../view/tools/ogpdashboard.phtml',
            'neuron/ncxtools/controller/tools/ogpdetail' => __DIR__ . '/../view/tools/ogpdetail.phtml',
            'neuron/ncxtools/controller/tools/downloaddetail' => __DIR__ . '/../view/tools/downloaddetail.phtml',
            'neuron/ncxtools/controller/tools/bulkupdate' => __DIR__ . '/../view/tools/bulkupdate.phtml',
            'neuron/ncxtools/controller/tools/bulkmove' => __DIR__ . '/../view/tools/bulkmove.phtml',
            'neuron/ncxtools/controller/tools/bulkmerge' => __DIR__ . '/../view/tools/bulkmerge.phtml',
            'neuron/ncxtools/controller/tools/bulktermin' => __DIR__ . '/../view/tools/bulkuptermin.phtml',
            'neuron/ncxtools/controller/tools/bulkorder' => __DIR__ . '/../view/tools/bulkorder.phtml',
            'neuron/ncxtools/controller/tools/inbox' => __DIR__ . '/../view/tools/inbox.phtml',
            'neuron/ncxtools/controller/dashboard/index' => __DIR__ . '/../view/dashboard/index.phtml',
            'neuron/ncxtools/controller/tools/sequence' => __DIR__ . '/../view/tools/sequence.phtml',
            'neuron/ncxtools/controller/tools/billing' => __DIR__ . '/../view/tools/billing.phtml',
            'neuron/ncxtools/controller/tools/detail-billing' => __DIR__ . '/../view/tools/detailbilling.phtml',
            'neuron/ncxtools/controller/tools/detail-sequence' => __DIR__ . '/../view/tools/detailsequence.phtml',
            'neuron/ncxtools/controller/tools/rekon' => __DIR__ . '/../view/rekon/rekon.phtml',
            'neuron/ncxtools/controller/tools/ca-custref' => __DIR__ . '/../view/rekon/cacustref.phtml',
            'neuron/ncxtools/controller/tools/ba-accnum' => __DIR__ . '/../view/rekon/baaccnum.phtml',
            'neuron/ncxtools/controller/tools/caba-custrefaacnum' => __DIR__ . '/../view/rekon/cabacustrefaacnum.phtml',
            'neuron/ncxtools/controller/tools/tibs-ncx' => __DIR__ . '/../view/rekon/tibsncx.phtml',
            'neuron/ncxtools/controller/tools/billcom-ncx-tibs' => __DIR__ . '/../view/rekon/billcomncxtibs.phtml',
            'neuron/ncxtools/controller/tools/tibs-ncx-billcom' => __DIR__ . '/../view/rekon/tibsncxbillcom.phtml',
            'neuron/ncxtools/controller/tools/ncx-tibs-sid' => __DIR__ . '/../view/rekon/ncxtibssid.phtml',
            'neuron/ncxtools/controller/tools/ncx-tibs-prince' => __DIR__ . '/../view/rekon/ncxtibsprince.phtml',
            'neuron/ncxtools/controller/tools/ncx-tibs-billdate' => __DIR__ . '/../view/rekon/ncxtibsbilldate.phtml',
            'neuron/ncxtools/controller/tools/ncx-tibs-ppn' => __DIR__ . '/../view/rekon/ncxtibsppn.phtml',
            'neuron/ncxtools/controller/tools/ncx-tibs-top' => __DIR__ . '/../view/rekon/ncxtibstop.phtml',
            'neuron/ncxtools/controller/tools/business-area' => __DIR__ . '/../view/rekon/businessarea.phtml',
            'neuron/ncxtools/controller/tools/tanggal-contract' => __DIR__ . '/../view/rekon/tanggalcontract.phtml',
            'neuron/ncxtools/controller/tools/cp-address' => __DIR__ . '/../view/rekon/cpaddress.phtml',
            'neuron/ncxtools/controller/tools/latlong' => __DIR__ . '/../view/rekon/latlong.phtml',
            'neuron/ncxtools/controller/tools/double-sid' => __DIR__ . '/../view/rekon/doublesid.phtml',
            'neuron/ncxtools/controller/tools/double-noparent' => __DIR__ . '/../view/rekon/doublenoparent.phtml',
            'neuron/ncxtools/controller/tools/missing-billing' => __DIR__ . '/../view/rekon/missingbilling.phtml',
            'neuron/ncxtools/controller/tools/double-ao' => __DIR__ . '/../view/rekon/doubleao.phtml',
            'neuron/ncxtools/controller/tools/double-mo' => __DIR__ . '/../view/rekon/doublemo.phtml',
            'neuron/ncxtools/controller/tools/double-mrc' => __DIR__ . '/../view/rekon/doublemrc.phtml',
            'neuron/ncxtools/controller/tools/ca-custref-detail' => __DIR__ . '/../view/rekon/cacustrefdetail.phtml',
            'neuron/ncxtools/controller/tools/ba-accnum-detail' => __DIR__ . '/../view/rekon/baaccnumdetail.phtml',
            'neuron/ncxtools/controller/tools/caba-custrefaacnum-detail' => __DIR__ . '/../view/rekon/cabacustrefaacnumdetail.phtml',
            'neuron/ncxtools/controller/tools/tibs-ncx-detail' => __DIR__ . '/../view/rekon/tibsncxdetail.phtml',
            'neuron/ncxtools/controller/tools/billcom-ncx-tibs-detail' => __DIR__ . '/../view/rekon/billcomncxtibsdetail.phtml',
            'neuron/ncxtools/controller/tools/tibs-ncx-billcom-detail' => __DIR__ . '/../view/rekon/tibsncxbillcomdetail.phtml',
            'neuron/ncxtools/controller/tools/ncx-tibs-sid-detail' => __DIR__ . '/../view/rekon/ncxtibssiddetail.phtml',
            'neuron/ncxtools/controller/tools/ncx-tibs-prince-detail' => __DIR__ . '/../view/rekon/ncxtibsprincedetail.phtml',
            'neuron/ncxtools/controller/tools/ncx-tibs-billdate-detail' => __DIR__ . '/../view/rekon/ncxtibsbilldatedetail.phtml',
            'neuron/ncxtools/controller/tools/ncx-tibs-ppn-detail' => __DIR__ . '/../view/rekon/ncxtibsppndetail.phtml',
            'neuron/ncxtools/controller/tools/ncx-tibs-top-detail' => __DIR__ . '/../view/rekon/ncxtibstopdetail.phtml',
            'neuron/ncxtools/controller/tools/business-area-detail' => __DIR__ . '/../view/rekon/businessareadetail.phtml',
            'neuron/ncxtools/controller/tools/tanggal-contract-detail' => __DIR__ . '/../view/rekon/tanggalcontractdetail.phtml',
            'neuron/ncxtools/controller/tools/cp-address-detail' => __DIR__ . '/../view/rekon/cpaddressdetail.phtml',
            'neuron/ncxtools/controller/tools/latlong-detail' => __DIR__ . '/../view/rekon/latlongdetail.phtml',
            'neuron/ncxtools/controller/tools/double-sid-detail' => __DIR__ . '/../view/rekon/doublesiddetail.phtml',
            'neuron/ncxtools/controller/tools/double-noparent-detail' => __DIR__ . '/../view/rekon/doublenoparentdetail.phtml',
            'neuron/ncxtools/controller/tools/missing-billing-detail' => __DIR__ . '/../view/rekon/missingbillingdetail.phtml',
            'neuron/ncxtools/controller/tools/double-ao-detail' => __DIR__ . '/../view/rekon/doubleaodetail.phtml',
            'neuron/ncxtools/controller/tools/double-mo-detail' => __DIR__ . '/../view/rekon/doublemodetail.phtml',
            'neuron/ncxtools/controller/tools/double-mrc-detail' => __DIR__ . '/../view/rekon/doublemrcdetail.phtml',
            'neuron/ncxtools/controller/tools/sid-ncx-noss' => __DIR__ . '/../view/rekon/sidncxnoss.phtml',
            'neuron/ncxtools/controller/tools/sid-ncx-noss-detail' => __DIR__ . '/../view/rekon/sidncxnossdetail.phtml',
            'neuron/ncxtools/controller/tools/sid-ncx-noss-asset' => __DIR__ . '/../view/rekon/sidncxnossasset.phtml',
            'neuron/ncxtools/controller/tools/sid-ncx-noss-asset-detail' => __DIR__ . '/../view/rekon/sidncxnossassetdetail.phtml',
            'neuron/ncxtools/controller/tools/ba-ncx-trems' => __DIR__ . '/../view/rekon/bancxtrems.phtml',
            'neuron/ncxtools/controller/tools/ba-ncx-trems-detail' => __DIR__ . '/../view/rekon/bancxtremsdetail.phtml',
            'neuron/ncxtools/controller/tools/rev-code' => __DIR__ . '/../view/rekon/revcode.phtml',
            'neuron/ncxtools/controller/tools/rev-code-detail' => __DIR__ . '/../view/rekon/revcodedetail.phtml',
            'neuron/ncxtools/controller/tools/ba-tibs-trems' => __DIR__ . '/../view/rekon/batibstrems.phtml',
            'neuron/ncxtools/controller/tools/ba-tibs-trems-detail' => __DIR__ . '/../view/rekon/batibstremsdetail.phtml',
            'neuron/ncxtools/controller/tools/fallout-nos' => __DIR__ . '/../view/rekon/falloutnos.phtml',
            'neuron/ncxtools/controller/tools/service-addr-ncx' => __DIR__ . '/../view/rekon/serviceaddrncx.phtml',
            'neuron/ncxtools/controller/tools/rekon-download' => __DIR__ . '/../view/rekon/rekondownload.phtml',
            'neuron/ncxtools/controller/tools/order-date-agreement' => __DIR__ . '/../view/rekon/orderdateagreement.phtml',
        ),
        'template_path_stack' => array(
            __DIR__ . '/../view',
        ),
    ),
);